language: c

notifications:
  email: false

script:
- make

before_deploy:
- tar -cvzf x86_64-gnu-linux.tar.gz abnf

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: VpYACnkyfO9JemaMlhRx0rLg0WTZYTl7AnZhXEjhLWeKP9N2VOzSlWx6q61/gI41q7SEOyDlH1iA0IEtj0DSxLZjLF/g35VbN4uLCoGZHi+jD2tjkSvnTjN3caoqw/i1RTOkvCi+UIMlYnz0DY+qOQE8d60DMShrlmEMVL2ODinx+AwSDWFo4Ekkt4dbLYNUQYu/VqgwErMfejsN93TMSqSXRmStkr7wFqqd3llao1//2F1wv206l+mGifVlQaB4okGf8m66WnVWWZKapv8t/Xy01rcy70RHd7xPE/tDQySLvH2C3zqCbSpDhS4abxxcuE4aBkopMQVednTBoVV95kbpv++Xw5NFOC3W95vKP+SAZ/opYq9QhVXKj7Aneo4Usq/Qgb37WSHDZWdtZ1YVXg9N0xlAYDJfT5O9L+WPS1ycjPHRWCq8RlIRY6Dfh/z0gaRDDMoomjX/WNi/Ia9QYS2u5BycSS5jFd0GMItIYJfvf6E/CTu/XmzSJ0a/dcaQYf8zuUpb6IiaJnWz8vlYOxtZyP1h1aagqPgNuNwowe09TevgJodHkacdIzq4e8ozpEPmjc3VWWyjCs9x5qyVfYtflIHlc2kOePXRC4Qj/DKQeOqv3qklLmjmybR1cV81hi+OeT4ML7FC+7jL6J2m+TD8qsVizgSHwH3Ic9GqnWk=
  file: x86_64-gnu-linux.tar.gz
  on:
    repo: squid-lang/abnf-validator
    tags: true
